# Generated by Django 3.1.1 on 2020-10-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.IntegerField(help_text="Unique Question's ID.", primary_key=True, serialize=False)),
                ('question_title', models.CharField(help_text="Enter Question's Title.", max_length=50)),
                ('question_text', models.CharField(help_text="Enter Question's Text.", max_length=500)),
                ('question_answer', models.CharField(help_text="Enter Question's Right Answer.", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your Name.', max_length=300)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text="Enter Choice's Text.", max_length=300)),
                ('choice_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.questions')),
            ],
        ),
    ]
