# Generated by Django 3.1.1 on 2020-10-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_questions_question_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_x',
        ),
    ]
