# Generated by Django 3.1.1 on 2020-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_questions_question_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='XValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_x',
        ),
    ]
