# Generated by Django 3.1.1 on 2020-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201014_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='xvalue',
            name='x_point',
            field=models.IntegerField(default=0),
        ),
    ]
